--- Makefile.orig       2009-08-02 17:31:34.000000000 +0200
+++ Makefile    2009-08-02 17:33:04.000000000 +0200
@@ -1,10 +1,8 @@
-PREFIX = /usr/local
+PREFIX = /usr
 BINDIR = ${PREFIX}/bin

-X11PREFIX = /usr/X11R6
-
-CFLAGS += -I${X11PREFIX}/include `pkg-config xft xrender xcomposite xdamage xfixes --cflags` -g -pedantic -Wall
-LDFLAGS += -L${X11PREFIX}/lib -lX11 -lm `pkg-config xft xrender xcomposite xdamage xfixes --libs`
+CFLAGS += -I/usr/include/X11 `pkg-config xft xrender xcomposite xdamage xfixes --cflags` -g -pedantic -Wall
+LDFLAGS += -L/usr/lib/X11 -lX11 -lm `pkg-config xft xrender xcomposite xdamage xfixes --libs`

 # Disable post-processing effects
 # CFLAGS += -DNOEFFECTS
