#!/bin/sh
#
# /etc/rc.d/wdm: start/stop X (wdm) display manager
#

case $1 in
start)
	. /etc/profile
	/usr/bin/wdm -nodaemon
	;;
stop)
	killall -q /usr/bin/wdm
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
