#!/bin/sh
#
# /etc/rc.d/monitd: start/stop monit daemon
#

CONFIG=/usr/etc/monitrc

case $1 in
  start)
    /usr/bin/monit -c $CONFIG
    ;;
  stop)
    /usr/bin/killall -q /usr/bin/monit
    ;;
  reload)
    /usr/bin/monit -c $CONFIG reload
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 [start|stop|reload|restart]"
    ;;
esac

# End of File
