#!/bin/sh
#
# /etc/rc.d/monitd: start/stop monit daemon
#

config_file=/etc/monitrc

case $1 in
  start)
    /usr/bin/monit -c ${config_file}
	  ;;
  stop)
    killall -q /usr/bin/monit
    ;;
  reload)
    /usr/bin/monit -c ${config_file} reload
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
	  ;;
  *)
	  echo "usage: $0 [start|stop|reload|restart]"
	  ;;
esac

# End of File
