#!/bin/sh
#
# /etc/rc.d/mlnetd: start/stop mldonkey daemon
#

MLDONKEY_USER=mldonkey
MLDONKEY_GROUP=mlusers
MLDONKEY_CHROOT=/var/mlnet

create_jail() {
  mkdir -p ${MLDONKEY_CHROOT}/{dev,etc,log,tmp}
  mknod ${MLDONKEY_CHROOT}/dev/null c 1 3
  mknod ${MLDONKEY_CHROOT}/dev/urandom c 1 9
  chmod 1775 ${MLDONKEY_CHROOT}/tmp
}

case $1 in
	start)
    [ ! -d ${MLDONKEY_CHROOT}/dev ] && create_jail
    export MLDONKEY_CHROOT
		/usr/bin/mlnet -run_as_user ${MLDONKEY_USER} 2>&1 >/${MLDONKEY_CHROOT}/log/mlnet.log &
		;;
	stop)
    killall -q /usr/bin/mlnet
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 [start|stop|restart]"
    ;;
esac

# End of file
