#!/bin/sh
#
# /etc/rc.d/mlnetd: start/stop mldonkey daemon
#

case $1 in
	start)
    export MLDONKEY_DIR=/var/mlnet
		mlnet -run_as_user mldonkey &
		;;
	stop)
    pkill mlnet
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 [start|stop|restart]"
    ;;
esac

# End of file
