#!/bin/sh

MLUSER=mldonkey
MLGROUP=mlusers
MLPATH=/var/mlnet


# check for mlusers group or add one if not exists
getent group $MLGROUP || groupadd $MLGROUP

# check for mldonkey user or add one
getent passwd $MLUSER || useradd -g $MLGROUP -m -d $MLPATH $MLUSER

# lock the account
passwd -l $MLUSER

# End of file
