#!/bin/sh
#
# /etc/rc.d/vboxd: start/stop VirtualBox daemon
#

VBOX_PATH=/usr/share/virtualbox/bin

case $1 in
  start)
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${VBOX_PATH}
    if [ -z "`pidof VBoxSVC`" -a "`lsmod | grep vboxdrv`" != "" ]; then
      ${VBOX_PATH}/VBoxSVC &>/dev/null &
    fi
    ;;
  stop)
    kill -TERM `pidof VBoxSVC` &>/dev/null
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: $0 [start|stop|restart]"
    ;;
esac

# End of file
